variables:
  ARM_CLIENT_ID: $(TF-ClientId)
  ARM_CLIENT_SECRET: $(Pipeline-ARM-ClientSecret)
  ARM_SUBSCRIPTION_ID: $(Pipeline-ARM-SubscriptionId)
  ARM_TENANT_ID: $(Pipeline-ARM-TenantId)

trigger:
- prod

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Terraform Init and Plan'
  inputs:
    azureSubscription: 'AzureRM-Chronokeys-Temp'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
      export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
      export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
      export ARM_TENANT_ID=$(ARM_TENANT_ID)

      terraform init -backend-config="resource_group_name=$(resourceGroupName)" \
                     -backend-config="storage_account_name=$(storage_account_name)" \
                     -backend-config="container_name=$(containerName)" \
                     -backend-config="key=$(key)" \
                     -input=false

      terraform plan -out=tfplan -input=false

- task: AzureCLI@2
  displayName: 'Terraform Apply'
  inputs:
    azureSubscription: 'AzureRM-Chronokeys-Temp'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
      export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
      export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
      export ARM_TENANT_ID=$(ARM_TENANT_ID)

      terraform apply tfplan -auto-approve